In [ ]:
from torch_geometric.datasets import Planetoid, CitationFull, NELL, LRGBDataset
from Proposed.proposed_dataset import ProposedDataset
import torch_geometric.transforms as T


DATASET_ROOT_FOLDER = "Datasets"

def get_citeseer_dataset():
    dataset = Planetoid(root = DATASET_ROOT_FOLDER,
                        name= "CiteSeer",
                        split='random')
    
    return dataset

def get_cora_dataset():
    dataset = Planetoid(root = DATASET_ROOT_FOLDER,
                        name= "Cora",
                        split='random')
    
    return dataset


def get_pubmed_dataset():
    dataset = Planetoid(root = DATASET_ROOT_FOLDER,
                        name= "PubMed",
                        split='random')
    
    return dataset

def get_nell_dataset():

    transform = T.RandomNodeSplit(split='random')

    dataset = NELL(root = DATASET_ROOT_FOLDER, transform=transform)
    
    return dataset


def get_proposed_dataset():
    dataset = ProposedDataset(root = DATASET_ROOT_FOLDER)
    
    return dataset

def get_lrgb_dataset(split='train'):
    dataset = LRGBDataset(root = DATASET_ROOT_FOLDER,
                        name= "Peptides-func",
                        split=split)
    
    return dataset

In [ ]:
lrgb_train = get_lrgb_dataset("train")
lrgb_test = get_lrgb_dataset("test")
lrgb_val = get_lrgb_dataset("val")

In [8]:
len(lrgb_train)

10873

In [31]:
lrgb_train.num_classes

10

In [32]:
lrgb_train.batch

AttributeError: 'LRGBDataset' object has no attribute 'batch'

In [14]:
lrgb_train[0].y.shape

torch.Size([460])

In [37]:
from torch_geometric.data import Batch
ff = Batch.from_data_list([lrgb_train])

AttributeError: 'NoneType' object has no attribute 'lower'

In [36]:
ff.batch

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [15]:
a = torch.empty((0, ), dtype=torch.int32)
torch.cat((a, lrgb_test[1].y), 0).shape

NameError: name 'torch' is not defined

In [ ]:
lrgb_test[1].y.shape

torch.Size([499])

In [16]:
train_output= "LRGB_Pep/train"
test_output= "LRGB_Pep/test"
val_output= "LRGB_Pep/val"

In [5]:
from torch_geometric.utils.convert import to_networkx
import networkx as nx

def make_all_edgelist(split):
    
    output_folder = train_output
    dataset = lrgb_train
    
    if split == 'test':
        output_folder = test_output
        dataset = lrgb_test
    elif split == 'val':
        output_folder = val_output
        dataset = lrgb_val

    for graph_number in range(len(dataset)):
        G = to_networkx(dataset[graph_number])
        nx.write_edgelist(G, f"{output_folder}/{graph_number}.edgelist")

In [18]:
make_all_edgelist('val')

FileNotFoundError: [Errno 2] No such file or directory: 'LRGB_Pep/val/0.edgelist'

In [ ]:
!pwd
lrgb.num_classes

/home/cail001usr/Documents/MSThesisCode


NameError: name 'lrgb' is not defined

In [ ]:
lrgb[104].edge_index

tensor([[  0,   0,   0,  ..., 489, 489, 489],
        [  1,  36,  37,  ..., 462, 484, 485]])

In [ ]:
G = to_networkx(dataset[0])
nx.write_edgelist(G, f"{output_folder}/{dataset_name}.edgelist")

In [38]:
lrgb_train[0].edge_attr

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [3, 0, 1],
        [0, 0, 0],
        [0, 0, 0]])

In [49]:
lrgb_train[103].y

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [63]:
lrgb_train[105].edge_attr

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [3, 0, 1],
        [3, 0, 1]])

In [9]:
from torch_geometric.utils.convert import to_networkx
import networkx as nx
print("kicu")
G = to_networkx(lrgb_train[0], [ lrgb_train[0].edge_attr])

kicu


KeyError: tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [3, 0, 1],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
G